# Версия файла конфигурации
version: 2

# Таймаут для выполнения линтера
timeout: 2m

# Включение и отключение линтеров
linters:
  enable:
    - errcheck         # Проверка необработанных ошибок
    - govet            # Анализатор govet (Go встроенный)
    - staticcheck      # Проверка кода на неиспользуемые переменные и функции
    - gosimple         # Проверка кода на излишнюю сложность
    - ineffassign      # Поиск неэффективных присваиваний
    - deadcode         # Поиск неиспользуемого кода
    - unused           # Проверка неиспользуемых переменных и функций
    - goconst          # Поиск повторяющихся строковых и числовых констант
    - gocritic         # Проверка кода на различные ошибки и предупреждения
    - gofmt            # Проверка форматирования кода
    - goimports        # Проверка порядка импортов
    - misspell         # Проверка орфографических ошибок в комментариях
    - whitespace       # Проверка лишних пробелов в коде
    - dupl             # Поиск дублирующегося кода
    - unconvert        # Обнаружение ненужных приведения типов
    - unparam          # Поиск неиспользуемых параметров функций
    - lll              # Проверка длины строк (ограничение 120 символов)
    - nakedret         # Запрещает использование голого return в функциях с >3 return-значениями
    - gosec            # Анализ кода на уязвимости в безопасности
    - nolintlint       # Проверка правильности использования `//nolint`
    - prealloc         # Рекомендация использовать `make` для срезов с известной длиной
    - stylecheck       # Проверка на соответствие стилю Go
    - exportloopref    # Выявляет замыкания, ссылающиеся на переменные в цикле
    - gocyclo          # Выявляет слишком сложные функции

  disable:
    - godot            # Отключение проверки наличия точки в конце комментария
    - funlen           # Отключение проверки длины функций

# Настройки линтеров
linters-settings:
  gocyclo:
    min-complexity: 15  # Разрешаем более сложные функции
  lll:
    line-length: 120    # Максимальная длина строки

# Исключаем определенные файлы и папки из проверки
exclude:
  - "testdata/*"       # Тестовые файлы
  - "migrations/*"     # SQL миграции
  - "vendor/*"         # Внешние библиотеки
  - "docs/*"           # Документация

# Исключаемые ошибки (если какие-то не критичны)
issues:
  exclude-rules:
    - linters:
        - errcheck
      text: ".*sql.*Close.*"  # Игнорируем ошибки закрытия соединений с БД

# Файлы, которые нужно проверять
run:
  skip-dirs:
    - "vendor"
    - "third_party"
    - "generated"

# Настройки форматирования кода (gofmt/goimports)
formatter:
  goimports:
    local-prefixes: "github.com/KsenoTech/merch-store"
