version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: merch_store_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: yourusername
      DB_PASSWORD: yourpassword
      DB_NAME: yourdatabase
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
