version: '3'
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: merch_store
    ports:
      - "5432:5432"
  
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASS: password
      DB_NAME: merch_store