services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 590789
      POSTGRES_DB: merch_store
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: merch_store_app
    environment:
      DATABASE_URL: postgres://postgres:590789@db:5432/merch_store?sslmode=disable
      SECRET_KEY: mySuperSecretKey123!@#ABCdef456
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
